# Generated by Django 4.1.7 on 2023-03-13 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('fullname', models.CharField(max_length=250)),
                ('form_name', models.CharField(max_length=250)),
                ('values', models.JSONField(default=dict)),
                ('forms_count', models.IntegerField(default=0)),
                ('image', models.ImageField(null=True, upload_to='media/images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'own_forms',
            },
        ),
        migrations.CreateModel(
            name='FilledForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, null=True)),
                ('fullname', models.CharField(max_length=250, null=True)),
                ('filled_form', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('counter', models.IntegerField(default=0)),
                ('form_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='own_forms.form', verbose_name='own_forms')),
            ],
            options={
                'db_table': 'filled_forms',
            },
        ),
    ]
